spring.application.name=activity1
spring.datasource.url=jdbc:mysql://localhost:3306/project342?useSSL=false&serverTimezone=UTC
spring.datasource.username=l23y19w32
spring.datasource.password=Welcome1!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true